### ISSUE TITLE
update connector to Trino 405

### ISSUE THREAD

**Issue by rponsaerts** [TileDB-Inc/TileDB-Trino#85]
Hi,

Would it be possible to update the TileDB-Trino connector to a more recent tag release 40x (405, 406)?

I have compiled Trino 357 with TileDB-Trino 1.12.0 support inside a singularity container (Rocky Linux), and testing goes well :)

However, I would like to query TileDB using Trino together with other data sources that need a more recent Trino version.

Not many tools can handle the datasets that I am querying using TileDB.

Thanks for creating and providing TileDB!

best,

raf

**Comment by Shelnutt2** [comment]
Hello @rponsaerts, thanks for opening the issue. It looks like updating to the latest Trino version will be straight forward. @DimitrisStaratzis will work on this this week and we hope to have a new release published before the end of the week. We'd also love to learn more about your usage of TileDB with Trino and the datasets your bringing in, would you be open to a short call to discuss more? Feel free to reach out to me at `seth@tiledb.com` and we can coordinate.

**Comment by Shelnutt2** [comment]
Hello @rponsaerts we've got a work in progress PR for the Trino update. The good news is we've gotten everything updated to the latest Trino version (https://github.com/TileDB-Inc/TileDB-Trino/pull/86). We are working through one last issue with a unit test and higher than expected memory usage. As such it looks like it'll be early next week before we can cut a release and provide the new jar. We'll let you know as soon as it is available.

**Comment by rponsaerts** [comment]
Thanks for the update and the agile, open support!

Looking forward to testing the upcoming release and providing feedback :)
